services:
  api:
    build: .
    command: npm run dev:api
    ports:
      - "3000:3000"

    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules

  worker:
    build: .
    command: npm run dev:worker

    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata: